name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - apis/userprofile/**
      - .github/workflows/ci/userprofile.test.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/userprofile/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/userprofile
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: npm install 
    - run: npm test
    # force error to force issue creation on failure
    # - run: exit 1
    - name: Create Issue on Failed Workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
