
name: POI api Testing

on:
  push:
    branches: [ main pb_poi ]
    paths:
      - apis/poi/**
  pull_request:
    branches: [ main pb_poi ]
    paths:
      - apis/poi/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/poi
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: dotnet build .
    - run: dotnet test .