name: tripsgo

env:
  ACR: superawesome2.azurecr.io
  STAGING_URL: https://openhack95e8pkj0trips-staging.azurewebsites.net
  PROD_URL: https://openhack95e8pkj0trips.azurewebsites.net
  RG: openhack95e8pkj0rg
  WEBAPP_NAME: openhack95e8pkj0trips

on:
  push:
    branches: [ main ]
    paths:
     - apis/trips/**
     - .github/workflows/tripsgo.yml
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go get

    - name: Test
      run: go test ./tripsgo -run Unit

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Execute Azure CLI Commands
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          cd apis/trips
          az acr build --image "mydriveway/api-tripsgo:${{ github.run_number }}" --registry superawesome2.azurecr.io --file Dockerfile .

    # - name: Docker Login
    #   run: docker login superawesome2.azurecr.io --username=${{SECRETS.CONTAINER_USER}} --password=${{SECRETS.CONTAINER_SECRET}}
    
    # - name: Docker build
    #   run: docker build -t superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}} .
      
    # - name: Docker push
    #   run: docker push superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}}

    - name : Deploy App Service 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images: "${{ env.ACR }}/mydriveway/api-tripsgo:${{ github.run_number }}"
        slot-name: staging
    
    - name: Validate Production
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: ${{ env.STAGING_URL }}
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"