name: Go

on:
  push:
    branches: [ main ]
    paths:
     - apis/trips/**
     - .github/workflows/tripsgo.yml
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    #- name: Build
    #  run: go build -v ./...

    - name: Test
      run: go test ./tripsgo -run Unit
