name: tripsgo

on:
  push:
    branches: [ main ]
    paths:
     - apis/trips/**
     - .github/workflows/tripsgo.yml
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go get

    - name: Test
      run: go test ./tripsgo -run Unit

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Execute Azure CLI Commands
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          cd apis/userprofile
          az acr build --image "mydriveway/api-tripsgo:${{ github.RUN_NUMBER }}" --registry superawesome2.azurecr.io --file Dockerfile .

    # - name: Docker Login
    #   run: docker login superawesome2.azurecr.io --username=${{SECRETS.CONTAINER_USER}} --password=${{SECRETS.CONTAINER_SECRET}}
    
    # - name: Docker build
    #   run: docker build -t superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}} .
      
    # - name: Docker push
    #   run: docker push superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack95e8pkj0trips'
        images: "superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}}"
        # slot-name: staging