name: tripsgo

env:
  ACR: superawesome2.azurecr.io
  STAGING_URL: https://openhack95e8pkj0trips-staging.azurewebsites.net
  PROD_URL: https://openhack95e8pkj0trips.azurewebsites.net
  STAGING_URL_HEALTH: https://openhack95e8pkj0trips-staging.azurewebsites.net/api/healthcheck/trips
  PROD_URL_HEALTH: https://openhack95e8pkj0trips.azurewebsites.net/api/healthcheck/trips
  RG: openhack95e8pkj0rg
  WEBAPP_NAME: openhack95e8pkj0trips

on:
  push:
    branches: [ main ]
    paths:
     - apis/trips/**
     - .github/workflows/tripsgo.yml
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go get

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login
      run: docker login superawesome2.azurecr.io --username=${{SECRETS.CONTAINER_USER}} --password=${{SECRETS.CONTAINER_SECRET}}
    
    - name: Docker build
      run: docker build -t superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}} .
      
    - name: Docker push
      run: docker push superawesome2.azurecr.io/mydriveway/api-tripsgo:${{GITHUB.RUN_NUMBER}}

    # - name: Test
    #   run: go test ./tripsgo -run Unit

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack95e8pkj0trips'
        images: "superawesome2.azurecr.io/mydriveway/api-tripsgo:${{ github.run_number }}"  #Can test with tag 20 temporarily
        slot-name: staging

    - name: Create Issue on Failed Workflow
      if: failure()
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
    - name: Validate Staging
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: ${{ env.STAGING_URL_HEALTH }}
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"

    - name: Swap staging to production
      run: |
        az webapp deployment slot swap --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RG }} --slot staging --target-slot production
    - uses: dacbd/create-issue-action@main
      if: failure()
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`

    - name: Validate_Production
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        #url: ${{ env.PROD_URL_HEALTH }}
        url: thisisasuperbadURLblahblahblah
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"
      
    - name: Rollback
      if: failure()
      run: |
        az webapp deployment slot swap --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RG }} --slot production --target-slot staging

# Deploy again to Staging after swap
    # - uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'openhack95e8pkj0trips'
    #     images: "superawesome2.azurecr.io/mydriveway/api-tripsgo:${{ github.run_number }}"  #Can test with tag 20 temporarily
    #     slot-name: staging