name: user-java

env:
  ACR: superawesome2.azurecr.io
  STAGING_URL: https://openhack95e8pkj0userjava-staging.azurewebsites.net
  PROD_URL: https://openhack95e8pkj0userjava.azurewebsites.net
  RG: openhack95e8pkj0rg
  WEBAPP_NAME: openhack95e8pkj0userjava

on:
  push:
    branches: [ main ]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/user-java/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/user-java
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          cd apis/user-java
          az acr build --image "mydriveway/api-user-java:${{ github.run_number }}" --registry superawesome2.azurecr.io --file Dockerfile .

    - name : Deploy App Service 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images: "${{ env.ACR }}/mydriveway/api-user-java:${{ github.run_number }}"
        slot-name: staging

    - name: Create Issue on Failed Workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
