name: userprofile

on:
  push:
    branches: [ main ]
    paths:
     - apis/userprofile/**
     - .github/workflows/userprofile.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/userprofile/**

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: apis/userprofile
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         node-version: '12'
#         cache: 'npm'
#     - run: npm install 
#     - run: npm test
#     # force error to force issue creation on failure
#     # - run: exit 1

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    # - name: Execute Azure CLI Commands
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.30.0
    #     inlineScript: |
    #       cd apis/userprofile
    #       ls -la
    #       az acr build --image "mydriveway/api-userprofile:${{ github.RUN_NUMBER }}" --registry superawesome2.azurecr.io --file Dockerfile .

    - name: Create Issue on Failed Workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`

    - name : Deploy App Service 
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'staging (openhack95e8pkj0userprofile/staging)'
        images: "mydriveway/api-userprofile:${{ github.RUN_NUMBER }}"
    
    - name: Show App Service Details
      run: |
        az appservice ase show --name api-userprofile